### PR TITLE
 feat: Add clang tidy support to CI

### PR DESCRIPTION
**Pull request by ciband**
## Proposed changes
Added clang tidy support to the clang CI target. As a first step warnings will not fail the build. Once we are down to 0 warnings, we can make warnings fail the build.

## Types of changes

- [X] Build (changes that affect the build system)

## Checklist

- [X] I have read the [CONTRIBUTING](https://docs.ark.io/guidebook/contribution-guidelines/contributing.html) documentation
- [X] Lint and unit tests pass locally with my changes

## Further comments
N/A

### CODE REVIEW

**Comment by ciband** [comment]
v1 tests are failing again.  Not sure why.  No test code was changed.

**Comment by sleepdefic1t** [comment]
Re: V1 tests.
Looks like the peer was syncing.
Not critical since it should be deprecated any time now.

**Comment by ciband** [comment]
Restarted CI to see if the v1 will pass now.  clang-tidy runs after the build/test step so I would like it to prove that it works.  It passed in my local CI.  Same code is running in cpp-crypto.

**Comment by sleepdefic1t** [comment]
All tests now passing 👍

**Pull request merged**
