### PR TITLE
ci: update arduino triggers

### PR DESCRIPTION
**Pull request by sleepdefic1t**
## Summary

This PR adjusts the Arduino CI paths for GH Actions.

## Checklist
- [ ] Documentation _(if necessary)_
- [ ] Tests _(if necessary)_
- [x] Ready to be merged

### CODE REVIEW

**Comment by sleepdefic1t** [comment]
@faustbrian
gtg 👍 

Hopefully this can help kick start the #126 workflow again too.

**Comment by faustbrian** [comment]
It would be better to use the GITHUB_WORKSPACE environment variable as documented at https://help.github.com/en/articles/virtual-environments-for-github-actions#environment-variables to avoid having to change that path if they do change it internally.

**Comment by sleepdefic1t** [comment]
@faustbrian 
Right on, the path only changed bc we switched to Actions which has different dir names, and the bash scripts copy to an Arduino library dir that has to be in home; so that workspace variable isn’t all that helpful in this case.

I can add it if you’d like, but we’d still need to use the system paths for the majority of the workflow.

**Comment by faustbrian** [comment]
Should something like `mv ${GITHUB_WORKSPACE}/* ~/Arduino/libraries/cpp-client/` work in that case if only the arduino folder has to stay where it is?

**Comment by faustbrian** [comment]
@sleepdefic1t https://github.com/ArkEcosystem/cpp-client/runs/238286766 looks good?

**Comment by sleepdefic1t** [comment]
@faustbrian 
Looks good to me 👍

**Pull request merged**
