### PR TITLE
feat: add 2.6 endpoints

### PR DESCRIPTION
**Pull request by dated**
## Summary

Adds the following API endpoints

**GET**

- [x] `bridgechains`
- [x] `bridgechains/{id}`
- [x] `businesses`
- [x] `businesses/{id}`
- [x] `businesses/{id}/bridgechains`
- [x] `wallets/{id}/locks`
- [x] `locks`
- [x] `locks/{id}`

**POST**

- [x] `businesses/search`
- [x] `bridgechains/search`
- [x] `locks/search`
- [x] `locks/unlocked`

## Checklist

- [ ] Documentation _(if necessary)_
- [x] Tests _(if necessary)_
- [ ] Ready to be merged

### CODE REVIEW

**Comment by sleepdefic1t** [comment]
@dated Looks like Paths::locks in `paths.cpp` is also missing its definitions.

**Comment by dated** [comment]
Thanks! I'll have a proper look asap

**Comment by sleepdefic1t** [comment]
@dated 

Are those API POST bodys correct?

I was only able to use these with Postman.

> search:
`{"lockId":"1916b6da532193a1703e53783b146835a98127445941efadb2d973932e2b8d33"}`

> unlocked:
`{ "ids":["1916b6da532193a1703e53783b146835a98127445941efadb2d973932e2b8d33"]}`

**Comment by dated** [comment]
I'll see what I can find in the core repository, there are docs available yet for the new endpoints :confused:

**Comment by dated** [comment]
https://github.com/ArkEcosystem/core/blob/3877e56cca98f32bbc620aea4973cf769761fd18/packages/core-api/src/handlers/locks/schema.ts#L40-L109

Indeed the `unlocked` endpoint accepts only an `ids` array.

**Comment by sleepdefic1t** [comment]
@dated 

nice! 😎 

Just to do a sanity check on the businesses endpoints,
Is `businessId` also the correct syntax? My TS isn't the strongest.

`https://github.com/ArkEcosystem/core/blob/ae1cb1d409302b18e8a94871f47c5432837e1f7a/__tests__/unit/core-database/repositories/blocks-business-repository.test.ts#L17`

The `https://dexplorer.ark.io/api/v2/businesses` endpoints only seems to load for me every few refreshes, and I'm not able to post anything at all to test against a live node.

**Comment by dated** [comment]
I'll do some tests and get back to you!

**Comment by dated** [comment]
```
> curl 'https://dexplorer.ark.io/api/v2/businesses/search' -H "Content-Type: application/json" -d '{ "businessId": "1" }'
{"meta":{"count":1,"pageCount":1,"totalCount":1,"next":null,"previous":null,"self":"/api/businesses/search?page=1&limit=100","first":"/api/businesses/search?page=1&limit=100","last":"/api/businesses/search?page=1&limit=100"},"data":[{"businessId":1,"name":"Devnet 0.42578625115310653","website":"dexplorer.ark.io"}]}
```

The schema validation will cast the given parameters to the types defined in the schema.

**Pull request merged**
