### PR TITLE
style: formatting and coverage

### PR DESCRIPTION
**Pull request by sleepdefic1t**
This PR is primarily concerned with fixing issues found in Codacy/Codefactor/Codecov/Google C++ Style Guide/etc.

This PR also merges #108 & #109 from master.

## What kind of change does this PR introduce?

- [x] Code style update

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Does this PR release a new version?

- [ ] Yes
- [x] No

**The PR fulfills these requirements:**

- [x] It's submitted to the `develop` branch, _not_ the `master` branch
- [x] All tests are passing
- [x] New/updated tests are included

### CODE REVIEW

**Comment by sleepdefic1t** [comment]
Codacy isn't configured for tracking `develop`.
Current build can be seen here: [codacy.com/project/sleepdefic1t/cpp-client](https://app.codacy.com/project/sleepdefic1t/cpp-client/dashboard?bid=13718297).
The only issues are related to the changelog, but it's pretty much exactly whats at [keepachangelog.com](https://keepachangelog.com). Changelog would likely need ignored in Codacy settings.

Otherwise, coverage stays at 100%, updates are in place and tests are passing.

This should be good to go, @faustbrian .

**Comment by sleepdefic1t** [comment]
This one's good to go too, @faustbrian.
Please and thank you.

**Comment by faustbrian** [comment]
@sleepdefic1t conflicts

**Comment by sleepdefic1t** [comment]
@faustbrian 
Codacy is still throwing a fit over CHANGELOG here.

This one's ready to go 👍

**Pull request merged**
