### PR TITLE
feat: add missing api endpoints

### PR DESCRIPTION
**Pull request by dated**
Adds the `rounds` API endpoints.

Adds the `transaction/fees` endpoint.

Adds the `node/fees` endpoint.

## What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Refactor
- [ ] Performance
- [ ] Tests
- [ ] Build
- [ ] Documentation
- [ ] Code style update
- [ ] Continuous Integration
- [ ] Other, please describe:

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Does this PR release a new version?

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `develop` branch, _not_ the `master` branch
- [x] All tests are passing
- [x] New/updated tests are included

If adding a **new feature**, the PR's description includes:

- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

### CODE REVIEW

**Comment by sleepdefic1t** [comment]
Thank you, @dated 

Are there currently any more Endpoints that need added?
That way we can just roll it all into one PR instead of adding them individually.

**Comment by dated** [comment]
I believe there's one more, `node/fees`.

**Comment by faustbrian** [comment]
Any more endpoints missing that should be added? So we can wrap them up in a single PR.

**Comment by dated** [comment]
The `node/fees` endpoint is missing.

**Comment by faustbrian** [comment]
Will have a look once the `node/fees` endpoint is added.

**Comment by dated** [comment]
@sleepdefic1t are you ok with the node/fees endpoint?

**Comment by sleepdefic1t** [comment]
Looks good and all tests pass on macOS for me.
Thank you, @dated 

@faustbrian 
This is good to go 👍

**Comment by dated** [comment]
:eyes:

**Pull request merged**
