### PR TITLE
chore: CodeClimate Improvements

### PR DESCRIPTION
**Pull request by sleepdefic1t**
## Summary

This PR resolves a couple code issues flagged in CodeClimate, CodeFactor, and Codacy.

Specifically, this PR does the following:
- `.appveyor.yml`
  - remove white space.
- `host.cpp`
  - use string.find() for correct host:port position.

## Checklist

- [x] Ready to be merged

### CODE REVIEW

**Comment by sleepdefic1t** [comment]
@faustbrian good to go 👍

**Comment by sleepdefic1t** [comment]
@faustbrian good to go 👍

**Comment by faustbrian** [comment]
Can't the .appveyor.yml file be deleted now that we don't use it anymore?

**Comment by sleepdefic1t** [comment]
@faustbrian 

Failing Coverage throws:
-  `Error: you must supply a CC_TEST_REPORTER_ID ENV variable or pass it via the -r flag`.

This is not related to these changes and is consistent with purpose of #148.
Coverage should run properly for subsequent PR's after merging.

**Pull request merged**
