### PR TITLE
chore: Update build to be out of source

### PR DESCRIPTION
**Pull request by ciband**
Updated build to be out of source to clean up the workspace
and added build scripts to enforce this.

Re-enabled  cmake_example builds in CI.

Removed cmake_example .gitmodules file.  This historically caused
git to do funny things having a nested .gitmodules in the source
tree.  Commented out the submodule clone in the CMakeList.txt and
setup the build script to mimic the submodule clone by copying the
cpp-crypto source into the correct directory.

## What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [x] Refactor
- [ ] Performance
- [ ] Tests
- [x] Build
- [ ] Documentation
- [ ] Code style update
- [ ] Continuous Integration
- [ ] Other, please describe:

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Does this PR release a new version?

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `develop` branch, _not_ the `master` branch
- [x] All tests are passing
- [ ] New/updated tests are included

If adding a **new feature**, the PR's description includes:

- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

### CODE REVIEW

**Comment by ciband** [comment]
Clang tidy is failing and I'm not sure why.  There is a lot of noise in the output from curl and what not.

I think a future PR to limit clang tidy file processing to not process submodules is needed.

We can either merge this PR as is or we can hold until we can reduce the clang tidy output such that the error is easier to spot.

**Comment by ciband** [comment]
Update:  It appears that clang tidy is failing on a curl source file:

Line 63249:
error: error reading '/home/circleci/project/src/lib/curl/src/tool_hugehelp.c' [clang-diagnostic-error]

Line 177893:
error: error reading '/home/circleci/project/src/lib/curl/tests/libtest/lib1521.c' [clang-diagnostic-error]

I do not know why.

**Comment by faustbrian** [comment]
@ciband conflicts

**Comment by ciband** [comment]
@sleepdefic1t  , @faustbrian Clang build failure looks like a circle ci issue.  I am unable to re-trigger, if desired.

**Pull request merged**
