### PR TITLE
Feat: Add GTest/GMock support for ESP32

### LINKED ISSUE #27: Use mocks for testing.
**Is your feature request related to a problem? Please describe.**

The current Cpp-Client tests use calls to actual nodes.
This ties the success of tests to the connected nodes state;
the aim should be to test the Cpp-Client's code independently.

**Describe the solution you'd like**

Use mock tests instead of sending requests to external nodes.

### PR DESCRIPTION
**Pull request by ciband**
## Proposed changes
Converts the IoT tests to use newly supported googletest and removes AUnit usage.  This re-enables the unit test builds for ESP32.

## Types of changes

- [X] Refactoring (improve a current implementation without adding a new feature or fixing a bug)
- [X] Build (changes that affect the build system)
- [X] Test (adding missing tests or fixing existing tests)
- [X] Other... Please describe: A lot of external to Ark work went into this feature (see details below)

## Checklist

- [X] I have read the [CONTRIBUTING](https://docs.ark.io/guidebook/contribution-guidelines/contributing.html) documentation
- [X] Lint and unit tests pass locally with my changes

## Further comments
This PR only supports ESP32, which is better than the current support of nothing.  The next step is to support ESP8266.  This is a work in progress.

googletest was not supported on our IoT platforms so I added support in googletest.  Ark has the distinction of being the first project to use this new feature.

The following are all the commits required to make this happen:

- https://github.com/google/googletest/pull/2000
- https://github.com/google/googletest/pull/2013
- https://github.com/google/googletest/pull/2027
- https://github.com/google/googletest/pull/2037
- https://github.com/google/googletest/pull/2041
- https://github.com/google/googletest/pull/2098
- https://github.com/google/googletest/pull/2107

Helps close #27

### CODE REVIEW

**Comment by ciband** [comment]
googletest PR has been merged and PIO appears to be updated but the actual downloaded library from PIO is still including the source file that is causing the duplicate symbols which cause the failing build.

Will continue to investigate.

**Comment by ciband** [comment]
There was an issue with the googletest PR.

This PR fixes it.

https://github.com/google/googletest/pull/2107

Waiting on it to be merged.

**Comment by ciband** [comment]
PR has been merged and PIO library is updated but the build still failed like the PIO library was not updated.  Will keep monitoring.

**Comment by ciband** [comment]
PIO library registry is updated and CI passes now.  This PR should be good to go.

**Comment by sleepdefic1t** [comment]
@ciband 

**macOS:**

`$ cd cpp-client/test`

`$ pio run -e esp32 -t upload`

```ascii
Processing esp32 (framework: arduino; platform: espressif32; board: esp32dev)
--------------------------------------------------------------------------------
LibraryManager: Installing id=64
Downloading...
Unpacking  [####################################]  100%
LibraryManager: Installing id=5976
Downloading...
Unpacking  [####################################]  100%
Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/espressif32/esp32dev.html
PLATFORM: Espressif 32 > Espressif ESP32 Dev Module
HARDWARE: ESP32 240MHz 320KB RAM (4MB Flash)
DEBUG: CURRENT(esp-prog) EXTERNAL(esp-prog, iot-bus-jtag, jlink, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny, tumpa)
Library Dependency Finder -> http://bit.ly/configure-pio-ldf
LDF MODES: FINDER(deep) COMPATIBILITY(soft)
Collected 42 compatible libraries
Scanning dependencies...
Dependency Graph
|-- <ArduinoJson> 5.13.4
|-- <googletest> 1.8.1
|-- <src>
|   |-- <HTTPClient> 1.2
|   |   |-- <WiFi> 1.2.7
|   |   |   |-- <SPI> 1.0
|   |   |-- <WiFiClientSecure> 1.0
|   |   |   |-- <WiFi> 1.2.7
|   |   |   |   |-- <SPI> 1.0
|-- <HTTPClient> 1.2
|   |-- <WiFi> 1.2.7
|   |   |-- <SPI> 1.0
|   |-- <WiFiClientSecure> 1.0
|   |   |-- <WiFi> 1.2.7
|   |   |   |-- <SPI> 1.0
Compiling .pioenvs/esp32/src/src/api/blocks/blocks.cpp.o
Compiling .pioenvs/esp32/src/src/api/delegates/delegates.cpp.o
Compiling .pioenvs/esp32/src/src/api/node/node.cpp.o
Compiling .pioenvs/esp32/src/src/api/paths.cpp.o
Compiling .pioenvs/esp32/src/src/api/peers/peers.cpp.o
Compiling .pioenvs/esp32/src/src/api/transactions/transactions.cpp.o
Compiling .pioenvs/esp32/src/src/api/votes/votes.cpp.o
Compiling .pioenvs/esp32/src/src/api/wallets/wallets.cpp.o
Compiling .pioenvs/esp32/src/src/host/host.cpp.o
Compiling .pioenvs/esp32/src/src/http/iot/http.cpp.o
Compiling .pioenvs/esp32/src/src/http/iot/main.cpp.o
Compiling .pioenvs/esp32/src/test/.piolibdeps/googletest_ID5976/googlemock/src/gmock-cardinalities.cc.o
Compiling .pioenvs/esp32/src/test/.piolibdeps/googletest_ID5976/googlemock/src/gmock-internal-utils.cc.o
Compiling .pioenvs/esp32/src/test/.piolibdeps/googletest_ID5976/googlemock/src/gmock-matchers.cc.o
Compiling .pioenvs/esp32/src/test/.piolibdeps/googletest_ID5976/googlemock/src/gmock-spec-builders.cc.o
Compiling .pioenvs/esp32/src/test/.piolibdeps/googletest_ID5976/googlemock/src/gmock.cc.o
Compiling .pioenvs/esp32/src/test/.piolibdeps/googletest_ID5976/googletest/src/gtest-death-test.cc.o
Compiling .pioenvs/esp32/src/test/.piolibdeps/googletest_ID5976/googletest/src/gtest-filepath.cc.o
Compiling .pioenvs/esp32/src/test/.piolibdeps/googletest_ID5976/googletest/src/gtest-matchers.cc.o
Compiling .pioenvs/esp32/src/test/.piolibdeps/googletest_ID5976/googletest/src/gtest-port.cc.o
Compiling .pioenvs/esp32/src/test/.piolibdeps/googletest_ID5976/googletest/src/gtest-printers.cc.o
Compiling .pioenvs/esp32/src/test/.piolibdeps/googletest_ID5976/googletest/src/gtest-test-part.cc.o
Compiling .pioenvs/esp32/src/test/.piolibdeps/googletest_ID5976/googletest/src/gtest-typed-test.cc.o
Compiling .pioenvs/esp32/src/test/.piolibdeps/googletest_ID5976/googletest/src/gtest.cc.o
Compiling .pioenvs/esp32/src/test/api/blocks.cpp.o
Compiling .pioenvs/esp32/src/test/api/delegates.cpp.o
Compiling .pioenvs/esp32/src/test/api/node.cpp.o
Compiling .pioenvs/esp32/src/test/api/paths.cpp.o
Compiling .pioenvs/esp32/src/test/api/peers.cpp.o
Compiling .pioenvs/esp32/src/test/api/transactions.cpp.o
Compiling .pioenvs/esp32/src/test/api/votes.cpp.o
Compiling .pioenvs/esp32/src/test/api/wallets.cpp.o
Compiling .pioenvs/esp32/src/test/connection/connection.cpp.o
Compiling .pioenvs/esp32/src/test/host/host.cpp.o
Compiling .pioenvs/esp32/src/test/iot/test_main.cpp.o
Generating partitions .pioenvs/esp32/partitions.bin
Archiving .pioenvs/esp32/lib622/libArduinoJson_ID64.a
Indexing .pioenvs/esp32/lib622/libArduinoJson_ID64.a
Compiling .pioenvs/esp32/lib192/googletest_ID5976/googlemock/src/gmock-cardinalities.cc.o
iot/test_main.cpp: In function 'void loop()':
iot/test_main.cpp:17:18: warning: ignoring return value of 'int RUN_ALL_TESTS()', declared with attribute warn_unused_result [-Wunused-result]
RUN_ALL_TESTS();
^
Compiling .pioenvs/esp32/lib192/googletest_ID5976/googlemock/src/gmock-internal-utils.cc.o
Compiling .pioenvs/esp32/lib192/googletest_ID5976/googlemock/src/gmock-matchers.cc.o
Compiling .pioenvs/esp32/lib192/googletest_ID5976/googlemock/src/gmock-spec-builders.cc.o
Compiling .pioenvs/esp32/lib192/googletest_ID5976/googlemock/src/gmock.cc.o
Compiling .pioenvs/esp32/lib192/googletest_ID5976/googletest/src/gtest-death-test.cc.o
Compiling .pioenvs/esp32/lib192/googletest_ID5976/googletest/src/gtest-filepath.cc.o
Compiling .pioenvs/esp32/lib192/googletest_ID5976/googletest/src/gtest-matchers.cc.o
Compiling .pioenvs/esp32/lib192/googletest_ID5976/googletest/src/gtest-port.cc.o
Compiling .pioenvs/esp32/lib192/googletest_ID5976/googletest/src/gtest-printers.cc.o
Compiling .pioenvs/esp32/lib192/googletest_ID5976/googletest/src/gtest-test-part.cc.o
Compiling .pioenvs/esp32/lib192/googletest_ID5976/googletest/src/gtest-typed-test.cc.o
Compiling .pioenvs/esp32/lib192/googletest_ID5976/googletest/src/gtest.cc.o
Compiling .pioenvs/esp32/lib60a/SPI/SPI.cpp.o
Compiling .pioenvs/esp32/lib518/WiFi_ID870/WiFi.cpp.o
Archiving .pioenvs/esp32/lib60a/libSPI.a
Indexing .pioenvs/esp32/lib60a/libSPI.a
Compiling .pioenvs/esp32/lib518/WiFi_ID870/WiFiClient.cpp.o
Compiling .pioenvs/esp32/lib518/WiFi_ID870/WiFiServer.cpp.o
Compiling .pioenvs/esp32/lib518/WiFi_ID870/WiFiUdp.cpp.o
Compiling .pioenvs/esp32/lib518/WiFi_ID870/utility/server_drv.cpp.o
Compiling .pioenvs/esp32/lib518/WiFi_ID870/utility/spi_drv.cpp.o
Compiling .pioenvs/esp32/lib518/WiFi_ID870/utility/wifi_drv.cpp.o
Compiling .pioenvs/esp32/lib5f3/WiFiClientSecure/WiFiClientSecure.cpp.o
.platformio/lib/WiFi_ID870/src/utility/spi_drv.cpp: In static member function 'static char SpiDrv::spiTransfer(char)':
.platformio/lib/WiFi_ID870/src/utility/spi_drv.cpp:36:78: warning: integer overflow in expression [-Woverflow]
#define DELAY_SPI(X) { int ii=0; do { asm volatile("nop"); } while (++ii < (X*F_CPU/16000000)); }
^
.platformio/lib/WiFi_ID870/src/utility/spi_drv.cpp:37:26: note: in expansion of macro 'DELAY_SPI'
#define DELAY_TRANSFER() DELAY_SPI(10)
^
.platformio/lib/WiFi_ID870/src/utility/spi_drv.cpp:76:5: note: in expansion of macro 'DELAY_TRANSFER'
DELAY_TRANSFER();
^
.platformio/lib/WiFi_ID870/src/utility/spi_drv.cpp: In static member function 'static void SpiDrv::getParam(uint8_t*)':
.platformio/lib/WiFi_ID870/src/utility/spi_drv.cpp:36:78: warning: integer overflow in expression [-Woverflow]
#define DELAY_SPI(X) { int ii=0; do { asm volatile("nop"); } while (++ii < (X*F_CPU/16000000)); }
^
.platformio/lib/WiFi_ID870/src/utility/spi_drv.cpp:37:26: note: in expansion of macro 'DELAY_SPI'
#define DELAY_TRANSFER() DELAY_SPI(10)
^
.platformio/lib/WiFi_ID870/src/utility/spi_drv.cpp:148:5: note: in expansion of macro 'DELAY_TRANSFER'
DELAY_TRANSFER();
^
.platformio/lib/WiFi_ID870/src/utility/wifi_drv.cpp: In static member function 'static uint8_t WiFiDrv::getEncTypeNetowrks(uint8_t)':
platformio/lib/WiFi_ID870/src/utility/wifi_drv.cpp:451:10: warning: converting to non-pointer type 'uint8_t {aka unsigned char}' from NULL [-Wconversion-null]
return NULL;
^
.platformio/lib/WiFi_ID870/src/utility/wifi_drv.cpp: In static member function 'static int32_t WiFiDrv::getRSSINetoworks(uint8_t)':
.platformio/lib/WiFi_ID870/src/utility/wifi_drv.cpp:476:10: warning: converting to non-pointer type 'int' from NULL [-Wconversion-null]
return NULL;
^
In file included from .platformio/lib/WiFi_ID870/src/utility/spi_drv.cpp:22:0:
.platformio/lib/WiFi_ID870/src/utility/spi_drv.h: At global scope:
.platformio/lib/WiFi_ID870/src/utility/spi_drv.h:41:13: warning: 'initialized' defined but not used [-Wunused-variable]
static bool initialized = false;
^
Compiling .pioenvs/esp32/lib5f3/WiFiClientSecure/ssl_client.cpp.o
Archiving .pioenvs/esp32/lib518/libWiFi_ID870.a
Indexing .pioenvs/esp32/lib518/libWiFi_ID870.a
.platformio/packages/framework-arduinoespressif32/libraries/WiFiClientSecure/src/WiFiClientSecure.cpp: In constructor 'WiFiClientSecure::WiFiClientSecure()':
.platformio/packages/framework-arduinoespressif32/libraries/WiFiClientSecure/src/WiFiClientSecure.cpp:33:5: error: '_connected' was not declared in this scope
_connected = false;
^
.platformio/packages/framework-arduinoespressif32/libraries/WiFiClientSecure/src/WiFiClientSecure.cpp: In constructor 'WiFiClientSecure::WiFiClientSecure(int)':
.platformio/packages/framework-arduinoespressif32/libraries/WiFiClientSecure/src/WiFiClientSecure.cpp:50:5: error: '_connected' was not declared in this scope
_connected = false;
^
platformio/packages/framework-arduinoespressif32/libraries/WiFiClientSecure/src/WiFiClientSecure.cpp: In member function 'WiFiClientSecure& WiFiClientSecure::operator=(const WiFiClientSecure&)':
.platformio/packages/framework-arduinoespressif32/libraries/WiFiClientSecure/src/WiFiClientSecure.cpp:79:5: error: '_connected' was not declared in this scope
_connected = other._connected;
^
.platformio/packages/framework-arduinoespressif32/libraries/WiFiClientSecure/src/WiFiClientSecure.cpp:79:24: error: 'const class WiFiClientSecure' has no member named '_connected'
_connected = other._connected;
^
platformio/packages/framework-arduinoespressif32/libraries/WiFiClientSecure/src/WiFiClientSecure.cpp: In member function 'virtual void WiFiClientSecure::stop()':
.platformio/packages/framework-arduinoespressif32/libraries/WiFiClientSecure/src/WiFiClientSecure.cpp:88:9: error: '_connected' was not declared in this scope
_connected = false;
^
.platformio/packages/framework-arduinoespressif32/libraries/WiFiClientSecure/src/WiFiClientSecure.cpp: In member function 'int WiFiClientSecure::connect(const char*, uint16_t, const char*, const char*, const char*)':
.platformio/packages/framework-arduinoespressif32/libraries/WiFiClientSecure/src/WiFiClientSecure.cpp:122:5: error: '_connected' was not declared in this scope
_connected = true;
^
.platformio/packages/framework-arduinoespressif32/libraries/WiFiClientSecure/src/WiFiClientSecure.cpp: In member function 'int WiFiClientSecure::connect(const char*, uint16_t, const char*, const char*)':
.platformio/packages/framework-arduinoespressif32/libraries/WiFiClientSecure/src/WiFiClientSecure.cpp:139:5: error: '_connected' was not declared in this scope
_connected = true;
^
.platformio/packages/framework-arduinoespressif32/libraries/WiFiClientSecure/src/WiFiClientSecure.cpp: In member function 'virtual size_t WiFiClientSecure::write(const uint8_t*, size_t)':
.platformio/packages/framework-arduinoespressif32/libraries/WiFiClientSecure/src/WiFiClientSecure.cpp:168:10: error: '_connected' was not declared in this scope
if (!_connected) {
^
.platformio/packages/framework-arduinoespressif32/libraries/WiFiClientSecure/src/WiFiClientSecure.cpp: In member function 'virtual int WiFiClientSecure::available()':
.platformio/packages/framework-arduinoespressif32/libraries/WiFiClientSecure/src/WiFiClientSecure.cpp:212:10: error: '_connected' was not declared in this scope
if (!_connected) {
^
.platformio/packages/framework-arduinoespressif32/libraries/WiFiClientSecure/src/WiFiClientSecure.cpp: In member function 'virtual uint8_t WiFiClientSecure::connected()':
.platformio/packages/framework-arduinoespressif32/libraries/WiFiClientSecure/src/WiFiClientSecure.cpp:228:12: error: '_connected' was not declared in this scope
return _connected;
^
*** [.pioenvs/esp32/lib5f3/WiFiClientSecure/WiFiClientSecure.cpp.o] Error 1
Compiling .pioenvs/esp32/libe28/HTTPClient/HTTPClient.cpp.o
.platformio/packages/framework-arduinoespressif32/libraries/WiFiClientSecure/src/ssl_client.cpp: In function 'int start_ssl_client(sslclient_context*, const char*, uint32_t, const char*, const char*, const char*, const char*, const char*)':
.platformio/packages/framework-arduinoespressif32/libraries/WiFiClientSecure/src/ssl_client.cpp:65:9: error: 'WiFiGenericClass' has not been declared
if(!WiFiGenericClass::hostByName(host, srv)){
^
*** [.pioenvs/esp32/lib5f3/WiFiClientSecure/ssl_client.cpp.o] Error 1
=========================================================================================================== [ERROR] Took 61.00 seconds ===========================================================================================================
```

**Comment by ciband** [comment]
Not sure what is going on there.  PIO build should be the same on Windows,Mac,Linux.  Works on Windows and Linux (via CI).

Do you have the latest PIO and platform updates installed?

**Comment by ciband** [comment]
You can try nuking the .pio* directories in the test directory and rebuild.  Looks like something with the ESP32 platform is not happy.

**Comment by sleepdefic1t** [comment]
@ciband 
Looks like I had to empty `~/.platformio/lib` 👍 
Now it builds and flashes okay.

However, ESP32 loops tests with:
```cpp
void setup() {
    Serial.begin(115200);
	while (!Serial); // for the Arduino Leonardo/Micro only
	delay(100);
  testing::InitGoogleMock();
	delay(1000);
}

void loop() {
  RUN_ALL_TESTS();
}
```

Changing to the following made tests run once on-board:
```cpp
void setup() {
    Serial.begin(115200);
	while (!Serial); // for the Arduino Leonardo/Micro only
	delay(100);
  testing::InitGoogleMock();
	delay(1000);
  RUN_ALL_TESTS();
}

void loop() { }
```

Can you confirm this?

**Comment by ciband** [comment]
Yes it does. If we want it to do a one-shit then we can do that. I will push a change.

**Comment by sleepdefic1t** [comment]
Thank you, @ciband !!
@kristjank @supaiku0 @faustbrian , this is ready to be merged 👍

**Pull request merged**
